# Generated by Django 5.1.5 on 2025-02-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='pizzaOrd.topping'),
        ),
    ]
