# Generated by Django 5.1.5 on 2025-02-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrd', '0002_order_address_alter_order_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='order',
            name='crust',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sauce',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaOrd.cheese')),
                ('crust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaOrd.crusttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizzaOrd.order')),
                ('sauce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaOrd.sauce')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaOrd.pizzasize')),
                ('toppings', models.ManyToManyField(blank=True, to='pizzaOrd.topping')),
            ],
        ),
    ]
