# Generated by Django 5.1.5 on 2025-02-12 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrd', '0003_remove_order_cheese_remove_order_crust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cheese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaOrd.cheese'),
        ),
        migrations.AddField(
            model_name='order',
            name='crust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaOrd.crusttype'),
        ),
        migrations.AddField(
            model_name='order',
            name='sauce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaOrd.sauce'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaOrd.pizzasize'),
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='pizzaOrd.topping'),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
